main:
  - name: Home
    url: /
    weight: 10
  - name: Research
    url: /research/
    weight: 20
  - name: Publications
    url: /publications/
    weight: 30
  - name: Teaching
    url: /teaching/
    weight: 40
  - name: CV
    url: /experience/
    weight: 50
  - name: Systemic Counseling
    url: /philosophical-counseling/
    weight: 60
  - name: Contact
    url: /contact/
    weight: 70